### ISSUE TITLE
[Rendering Crash]: RotaryCraft + Stacks on Stacks

### ISSUE THREAD

**Issue by Lanse505** [TierZeroProductions/StacksOnStacks#38] opened 2015-10-25 23:05 UTC
CrashLog: http://pastebin.com/e2HZCEXx

**Comment by XFactHD** [comment] 2015-10-26 01:47
Can you reproduce this without ForgeRelocation?

**Comment by primetoxinz** [comment] 2015-10-26 02:13
yeah, what makes you think this is rotarycraft?

**Comment by Lanse505** [comment] 2015-10-26 02:16
1. ForgeRelocation is a Library within Project Red that allows for the moving of blocks with frame.

2. Cause it happens when I create an "Gem Pile" with any of the "Gems" from Rotarycraft.

**Comment by Madxmike** [comment] 2015-10-26 02:33
Pretty sure this is caused by the same thing as #34 so im closing it as a duplicate.

**Closed by Madxmike** 2015-10-26 02:33 UTC
Labels: bug, duplicate
